# Generated by Django 4.2.28 on 2026-02-04 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(default="#6B7280", max_length=7)),
                ("is_predefined", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="current_period_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Tracks completions in current recurrence period"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="keep_history",
            field=models.BooleanField(
                default=True,
                help_text="If True, completed occurrences remain visible; if False, task resets",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to parent recurring task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="occurrences",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="period_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date of current recurrence period",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_pattern",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="times_per_period",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of times to complete per period (e.g., 3 times per week)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["recurrence_pattern"], name="tasks_task_recurre_aab063_idx"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tasks.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="tag",
            index=models.Index(
                fields=["user", "is_predefined"], name="tasks_tag_user_id_81dbeb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("user", "name")},
        ),
    ]
