# Generated by Django 4.2.28 on 2026-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("tasks", "0003_add_tags_and_recurrence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tags.tag"
            ),
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
